services:
  mc-server:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "${PORT:-19132}:${PORT:-19132}"
    volumes:
      - server:/home/container
    environment:
      - BEDROCK_VERSION=${BEDROCK_VERSION:-latest}
    command: bash -c "/entrypoint.sh && /get.sh && ./bedrock_server"

volumes:
  server:
